// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZSND7Cqyz9EYnncMu9ci6oFHa7zRXQ0k',
    appId: '1:89488273604:web:571c1baa85d832d8a3d991',
    messagingSenderId: '89488273604',
    projectId: 'colorlab-d9ff8',
    authDomain: 'colorlab-d9ff8.firebaseapp.com',
    storageBucket: 'colorlab-d9ff8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9CUWgzhqlpoiRP1A7h2gTNN8-1jsAfM',
    appId: '1:89488273604:android:43c8dd5f4d833fc8a3d991',
    messagingSenderId: '89488273604',
    projectId: 'colorlab-d9ff8',
    storageBucket: 'colorlab-d9ff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD72gQZMp5-vvxQiBEoRfMcRByyykxViA',
    appId: '1:89488273604:ios:6903177c0e0ed68fa3d991',
    messagingSenderId: '89488273604',
    projectId: 'colorlab-d9ff8',
    storageBucket: 'colorlab-d9ff8.appspot.com',
    iosClientId: '89488273604-m0761k4llho5h7qhfen54qu7qbnlvu7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD72gQZMp5-vvxQiBEoRfMcRByyykxViA',
    appId: '1:89488273604:ios:6903177c0e0ed68fa3d991',
    messagingSenderId: '89488273604',
    projectId: 'colorlab-d9ff8',
    storageBucket: 'colorlab-d9ff8.appspot.com',
    iosClientId: '89488273604-m0761k4llho5h7qhfen54qu7qbnlvu7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorPages',
  );
}
